version: "1.0"

# Concurrency settings
concurrency:
  max_workers: 4
  timeout_seconds: 3600

# Retry settings
retry: 
  max_attempts: 3
  retry_delay_seconds: 5

# Source Databricks Connect configuration
source_databricks_connect_config: 
  host: "https://source-databricks-instance"
  token: 
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"

# Target Databricks Connect configuration
target_databricks_connect_config: 
  host: "https://target-databricks-instance"
  token: 
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"    

# Delta share configuration
delta_share_config: 
  enabled: true
  recipient_id: "azure_recipient"
  shares:
    - share_name: "main_share"
      catalog_name: "aaron"
      schema_suffix: "_share"
      shared_catalog_name: "aaron_aws"
      schemas:
        - schema_name: "source_schema"

# backup configuration
backup_config:
  enabled: true
  audit_log_table: "operations.audit.backup_logs"
  catalogs:
    - catalog_name: "aaron"
      backup_catalog: "backup_catalog"
      schemas:
        - schema_name: "source_schema"
          backup_schema: "backup_source_schema"
        - schema_name: "analytics_schema"
          backup_schema_suffix: "_backup"
          tables:
            - table_name: "product_metrics"
            - table_name: "sales_data"
        - schema_name: "source_schema2"
          exclude_tables:
            - table_name: "temp_table"

# replication configuration
replication_config:
  enabled: true
  audit_log_table: "operations.audit.replication_logs"
  enforce_schema: true
  catalogs:
    - catalog_name: "aaron"
      intermediate_catalog: "intermediate_catalog"
      source_catalog: "source_catalog"
      schemas:
        - schema_name: "target_schema"
          source_schema: "source_schema"
        - schema_name: "analytics_schema"
          source_schema_suffix: "_backup"
          tables:
            - table_name: "product_metrics"
            - table_name: "sales_data"
        - schema_name: "target_schema2"
          exclude_tables:
            - table_name: "temp_table"

# reconciliation configuration
reconciliation_config:
  enabled: true
  audit_log_table: "operations.audit.reconciliation_logs"
  recon_outputs_catalog: "recon_results"
  schema_check: true
  row_count_check: true
  missing_data_check: true
  catalogs:
    - catalog_name: "aaron"
      source_catalog: "source_catalog"
      schemas:
        - schema_name: "target_schema"
          source_schema: "source_schema"
        - schema_name: "analytics_schema"
          source_schema_suffix: "_backup"
          tables:
            - table_name: "product_metrics"
            - table_name: "sales_data"
        - schema_name: "target_schema2"
          exclude_tables:
            - table_name: "temp_table"