version: "1.0"

# Source Databricks Connect configuration
source_databricks_connect_config:
  host: "https://source-databricks-instance"
  token:
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"

# Target Databricks Connect configuration
target_databricks_connect_config:
  host: "https://target-databricks-instance"
  token:
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"   

# replicator configuration
target_catalogs:
  - catalog_name: "aaron"
    schema_filter_expression: "databaseName like 'bonze_%'"
    backup_config:
      enabled: true
      source_catalog: "aaron"       
      backup_catalog: "aaron_dr"
      audit_log_table: "operations.audit.backup_logs"
    delta_share_config:
      enabled: true
      recipient_id: "azure_recipient"
      shared_catalog: "aaron_dr"        
      share_name: "aaron_dr_aws"
      shared_catalog_name: "aaron_dr_aws_shared"
    replication_config:
      enabled: true
      source_catalog: "aaron_dr_aws_shared"
      intermediate_catalog: "aaron_dr"
      enforce_schema: true
      audit_log_table: "operations.audit.replication_logs"
    reconciliation_config:
      enabled: true
      delta_share_config:
        enabled: true
        recipient_id: "azure_recipient"
        shared_catalog: "aaron"       
        share_name: "aaron_aws"
        shared_catalog_name: "aaron_aws_shared"
      source_catalog: "aaron_aws_shared"
      audit_log_table: "operations.audit.reconciliation_logs"
      recon_outputs_catalog: "recon_results"
      schema_check: true
      row_count_check: true
      missing_data_check: true
    target_schemas:
      - schema_name: "bonze_1"
      - schema_name: "bonze_2"
        tables:
          - table_name: "product_metrics"
          - table_name: "sales_data"
      - schema_name: "bonze_3"
        exclude_tables:
          - table_name: "temp_table"

# Concurrency settings
concurrency:
  max_workers: 4
  timeout_seconds: 3600

# Retry settings
retry:
  max_attempts: 3
  retry_delay_seconds: 5