version: "1.0"

source_databricks_connect_config:
  host: "https://adb-984752964297111.11.azuredatabricks.net"
  token:
    secret_scope: "test_kr"
    secret_key: "pat_source"

target_databricks_connect_config:
  host: "https://e2-demo-field-eng.cloud.databricks.com"
  token:
    secret_scope: "test_kr"
    secret_key: "pat_target"

audit_config:
  audit_table: "aaron.audit.audit_loggging"

target_catalogs:
  - catalog_name: "aaron"
    schema_filter_expression: "databaseName like 'bronze_%'"
    backup_config:
      enabled: true
      source_catalog: "aaron"
      backup_catalog: "aaron_dr"
    target_schemas:
      - schema_name: "bronze_1"
        tables:
          - table_name: "table_1"
          - table_name: "table_2"          
          - table_name: "sample_trips_ldp"
        exclude_tables:
          - table_name: "table_3"

concurrency:
  max_workers: 2
  timeout_seconds: 1800

retry:
  max_attempts: 2
  retry_delay_seconds: 3