version: "1.0"

# Source Databricks Connect configuration
source_databricks_connect_config:
  host: "https://source-databricks-instance"
  token:
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"

# Target Databricks Connect configuration
target_databricks_connect_config:
  host: "https://target-databricks-instance"
  token:
    secret_scope: "my_secret_scope"
    secret_key: "my_secret_key"   

audit_config:
  audit_table: "enterprise.audit.mct_audit_logging"
  
# replicator configuration
target_catalogs:
  - catalog_name: "enterprise"
    schema_filter_expression: "databaseName like '%_bonze'"
    backup_config:
      enabled: true
      source_catalog: "enterprise"
      backup_catalog: "enterprise_dr"
    replication_config:
      enabled: true
      delta_share_config:
        enabled: true
        recipient_id: "azure_recipient"
        shared_catalog: "enterprise_dr"
        share_name: "enterprise_dr_aws"
        shared_catalog_name: "enterprise_dr_aws_shared"
      source_catalog: "enterprise_dr_aws_shared"
      intermediate_catalog: "enterprise_dr"
      enforce_schema: true
    reconciliation_config:
      enabled: true
      delta_share_config:
        enabled: true
        recipient_id: "azure_recipient"
        shared_catalog: "enterprise"
        share_name: "enterprise_aws"
        shared_catalog_name: "enterprise_aws_shared"
      source_catalog: "enterprise_aws_shared"
      recon_outputs_catalog: "recon_results"
      schema_check: true
      row_count_check: true
      missing_data_check: true
    target_schemas:
      - schema_name: "BA0907_bonze"
      - schema_name: "BA0915_bonze"
        tables:
          - table_name: "product_metrics"
          - table_name: "sales_data"

# Concurrency settings
concurrency:
  max_workers: 4
  timeout_seconds: 3600

# Retry settings
retry:
  max_attempts: 3
  retry_delay_seconds: 5