version: "1.0"

replication_group: "aaron_test_group1"

execute_at: "target"

source_databricks_connect_config:
  name: "azure"
  host: "https://adb-984752964297111.11.azuredatabricks.net"
  token:
    secret_scope: "test_kr"
    secret_key: "pat_source"

target_databricks_connect_config:
  name: "aws"
  host: "https://e2-demo-field-eng.cloud.databricks.com"
  token:
    secret_scope: "test_kr"
    secret_key: "pat_target"

audit_config:
  audit_table: "aaron.audit.audit_logging"

target_catalogs:
  - catalog_name: "aaron"
    backup_config:
      enabled: true
    replication_config:
      enabled: true
    reconciliation_config:
      enabled: true
      source_catalog: aaron_azure_shared
      recon_outputs_catalog: aaron_azure_shared_recon_results
      recon_outputs_schema: recon_outputs
    target_schemas:
      - schema_name: "bronze_1"
        # tables:
          # - table_name: "table_3"
        #   # - table_name: "table_1"
        #   # - table_name: "table_2"
        #   # - table_name: "sample_trips_ldp"
        #   # - table_name: "delta_table_1"
        #   # - table_name: "mat_view1"
        #   # - table_name: "mat_view2"
        #   # - table_name: "mat_view3"
        #   # - table_name: "mat_view4"
        #   # - table_name: "mat_view5"
        #   # - table_name: "mat_view6"
        #   # - table_name: "mat_view7"
        #   # - table_name: "mat_view8"
        #   - table_name: "mat_view9"
        # exclude_tables:
        #   - table_name: "table_3"

concurrency:
  max_workers: 5
  timeout_seconds: 1800

retry:
  max_attempts: 2
  retry_delay_seconds: 3
